#ifndef CAMERALIB_GLOBAL_H
#define CAMERALIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMERALIB_LIBRARY)
#  define CAMERALIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAMERALIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERALIB_GLOBAL_H
